src/ConceptCave.www/Areas/Player/Controllers/PlayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConceptCave.BusinessLogic.LingoDataObjects;
using ConceptCave.Data.EntityClasses;
using ConceptCave.Repository;
using ConceptCave.Checklist.Interfaces;
using ConceptCave.RepositoryInterfaces.Enums;
using ConceptCave.www.Areas.Player.Models;
using ConceptCave.Checklist.RunTime;
using ConceptCave.Data.HelperClasses;
using System.Transactions;
using ConceptCave.Repository.Facilities;
using System.Dynamic;
using ConceptCave.www.Services;
using ConceptCave.Checklist.Facilities;
using ConceptCave.Checklist.Commands.Runtime;

namespace ConceptCave.www.Areas.Player.Controllers
{
    public class PlayController : ControllerBase
    {
        public ActionResult Index()
        {
            //very simple, return the angular app
            return View();
        }

    }
}

src/ConceptCave.www/Views/Play/Action.cshtml
@model ConceptCave.www.Areas.Player.Models.AnswerModel
@Html.Raw(Json.Encode(Model))

src/ConceptCave.www/Views/Play/Back.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModel

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('setModel', @Html.Raw(Json.Encode(Model.AnswerModel)));
    })
</script>
@Html.Partial(Model.Item.PartialView, Model.Item)

src/ConceptCave.www/Views/Play/Finished.cshtml
@model ConceptCave.www.Areas.Player.Models.FinishedModel
@{
    this.Layout = null;
}
        <h3 translate>Finished</h3>

        <p translate>Thank you the @Model.ChecklistName checklist has been completed.</p>

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('finished');
    })
</script>

src/ConceptCave.www/Views/Play/Index.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModel
@{
    ViewBag.Title = "Index";
    ViewBag.BodyClass = "player";
    
    if(Model.IsAjax)
    {
        this.Layout = null;   
    }
    
    if(Model.RunMode == ConceptCave.Checklist.Interfaces.RunMode.Blocked)
    {
        <p translate>This is blocked at the moment</p>   
    
        return;
    }
}

<script type="text/javascript">
    $(function () {
        var finishingcallback = function() {
            $("#navtools").hide('puff', {}, 'slow');
            $("#finishContainer").show('slide', {direction: "right"}, 'slow');
        };

        var finishedcallback = function() {
            if($("#navtools").css('display') != "none")
            {
                $("#navtools").hide('puff', {}, 'slow');
            }
        };

        var player = $("body").checklistplayer('init', { nextModelField: "#playnext_answermodel", playerElement: $("#playerview") });

        $("body").die("finishing");
        $("body").live("finishing", finishingcallback);

        $("body").die("finished");
        $("body").live("finished", finishedcallback);

        $("body").live('modelchanged', function(event, data) {
            if(data == undefined)
            {
                return;
            }

            if(data.CanPrevious == true)
            {
                $("#back").show('fade');
            }
            else{
                $("#back").hide('fade');
            }
            if(data.CanNext == true)
            {
                $("#next").show('fade');
            }
            else{
                $("#next").hide('fade');
            }
        });

        $("body").live('action', function(event, data) {
            $("#playaction_answermodel").val(data.data);
            CurrentDesignerManager.submitForm($("#playaction"), function (responseText) {
                data.callback(jQuery.parseJSON(responseText));
            });
        });

        player.checklistplayer('setModel', @Html.Raw(Json.Encode(Model.AnswerModel)));
    })
</script>

@if (Model.Program.RunMode.Value != ConceptCave.Checklist.Interfaces.RunMode.Finished)
{ 
<div id="navtools" class="subnav @(Model.IsAjax == true ? "" : "subnav-fixed")">
    <div class="container">
        <button class="btn btn-success" id="back" type="button"><i class="icon-circle-arrow-left icon-white"></i>&nbsp;<translate>Back</translate></button>
        <button class="btn btn-success" id="next" type="button"><translate>Next</translate>&nbsp;<i class="icon-circle-arrow-right icon-white"></i></button>
    </div>
</div>
<div class="clear">&nbsp;</div>
}

<div class="playercontent">
    <div id="playerview">
        @Html.Partial(Model.Item.PartialView, Model.Item)
    </div>

    <div id="finishContainer" style="display:none">
        <button class="btn btn-success" id="finish" type="button"><i class="icon-ok icon-white"></i>&nbsp;<translate>Finish</translate></button>
    </div>
</div>

<div class="playerprocessing" id="playerprocessing" style="display:none;">
    &nbsp;
</div>

<!--
<div style="float:left;width:18%">
    <br />
    <div>
        <div class="section">
            <h4>Reference Material</h4>
            <table>
                @foreach (var reference in Model.ReferenceMaterials)
                {
                    <tr>
                        <td>
                            <a href="@reference.Url" target="_blank">@reference.Name</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>
-->

<div style="clear:both">&nbsp;</div>

@using (Html.BeginForm("Next", "Play", FormMethod.Post, new { id = "playnext" }))
{
    @Html.Hidden("answermodel", "", new { id = "playnext_answermodel" });
}

@using (Html.BeginForm("Back", "Play", FormMethod.Post, new { id = "playback" }))
{
    @Html.Hidden("rootid", @Model.AnswerModel.RootId);
}

@using (Html.BeginForm("Finish", "Play", FormMethod.Post, new { id = "playfinish" }))
{
    @Html.Hidden("rootid", @Model.AnswerModel.RootId);
}

@using (Html.BeginForm("GetNotes", "Play", FormMethod.Post, new { id = "playgetnotes" }))
{
    @Html.Hidden("rootid", @Model.AnswerModel.RootId);
    @Html.Hidden("presentedId", "", new { id = "playgetnotes_presentedId" });
}

@using (Html.BeginForm("Action", "Play", FormMethod.Post, new { id = "playaction" }))
{
    @Html.Hidden("answermodel", "", new { id = "playaction_answermodel" });
}

<div class="modal hide fade" id="editnotesdialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3 translate>Notes</h3>
    </div>
    <div class="modal-body" id="editnotesdialogbody">
        <p translate>Loading ...</p>
    </div>
    <div class="modal-footer">
        <a href="#" id="editnotesdialogsave" class="btn btn-primary" translate>Save</a>
        <a href="#" class="btn" data-dismiss="modal" translate>Close</a>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        var options = {
            rootUrl: '@Url.ToFullyQualifiedUrl("~/")',
        };

        CreateDesignerManager(options);

        SquareIT.UIShowProcessing = function() {
            var position = $("#playerview").offset();
            $(".playerprocessing").css( { position: "absolute", left: position.left - 10, top: position.top, display:"inherit" } );
        };

        SquareIT.UIHideProcessing = function() {
            $(".playerprocessing").css( { display:"none" });
        };

        var doNext = function()
        {
            if ($("body").checklistplayer('next') == true) {

                // position and show the overlay
                SquareIT.UIShowProcessing();

                CurrentDesignerManager.submitForm($("#playnext"), function (responseText, angularise) {
                    $("#playerview").hide('slide', {direction: "left" }, 'slow', function() {
                        $("#playerview").html(responseText);
                        $("#playerview").show('slide', {direction: "right" }, 'slow');
                        SquareIT.UIHideProcessing();
                        angularise($("#playerview"));
                    });
                });
            }
        }

        var doBack = function()
        {
            if($("body").checklistplayer('back'))
            {
                SquareIT.UIShowProcessing();
                CurrentDesignerManager.submitForm($("#playback"), function (responseText, angularise) {
                    $("#playerview").hide('slide', {direction: "right" }, 'slow', function() {
                        $("#playerview").html(responseText);
                        $("#playerview").show('slide', {direction: "left" }, 'slow');
                        SquareIT.UIHideProcessing();
                        angularise($("#playerview"));
                    });
                }); 
            }
        }

        $("#next").click(function () {
            doNext();
        });

        $("#back").click(function () { 
            doBack();
        });

        $("#finish").click(function() {
            $("#finishContainer").hide('slide', {direction: "left" }, 'slow', function() {

                CurrentDesignerManager.submitForm($("#playfinish"), function (responseText, angularise) {
                    $("#playerview").hide('slide', {direction: "right" }, 'slow', function() {
                        $("#playerview").html(responseText);
                        $("#playerview").show('slide', {direction: "left" }, 'slow');

                        $("#playerview").trigger('finishedchecklist', {id: '@Model.AnswerModel.RootId'});
                        angularise($("#playerview"));
                    });
                }); 
            });
        });

        CreateDialogManager($("#modaldialog"), $("#modaldialogcontent"), $("#savemodaldialog"), 500);

        $("#savemodaldialog").button();

        $("body").die('notesrequired');
        $("body").live('notesrequired', function(event, data) {
            $("#playgetnotes_presentedId").val(data);
            
            $("#editnotesdialogbody").text($ng_translate("loading..."));
            $("#editnotesdialog").modal();

            CurrentDesignerManager.submitForm($("#playgetnotes"), $("#editnotesdialogbody")); 
        });

        $("#editnotesdialogsave").die('click');
        $("#editnotesdialogsave").live('click', function() {
            var select = "#editnotesdialogbody form:nth-child(1)";

            CurrentDesignerManager.submitForm($(select)[0], function (responseText) {
                CurrentDialogManager.close();
                $('#editnotesdialog').modal('hide');
            });
        });

        @if (Model.Program.WorkingDocument.RunMode == ConceptCave.Checklist.Interfaces.RunMode.Finished &&  Model.Program.WorkingDocument.FinishMode == ConceptCave.Checklist.Interfaces.FinishMode.Auto)
        {
            <text>$("body").checklistplayer('finished');</text>
        }
            
    })
</script>

src/ConceptCave.www/Views/Play/Next.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModel

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('setModel', @Html.Raw(Json.Encode(Model.AnswerModel)));
    })
</script>
@Html.Partial(Model.Item.PartialView, Model.Item)

src/ConceptCave.www/Views/Play/RenderCheckboxPlayer.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModelItem
@{
    this.Layout = null;

    ConceptCave.Checklist.Interfaces.ILingoProgram program = Model.PlayerModel.Program;
    ConceptCave.Checklist.Interfaces.IPresentedQuestion presented = (ConceptCave.Checklist.Interfaces.IPresentedQuestion)Model.Presented;
    ConceptCave.Checklist.Editor.CheckboxQuestion question = (ConceptCave.Checklist.Editor.CheckboxQuestion)presented.Question;
    var answer = presented.GetAnswer() as ConceptCave.Checklist.Interfaces.ICheckboxAnswer;

    var returnId = presented.Id.ToString();
    if (Model.PlayerModel.Context.Area == ConceptCave.www.Areas.Player.Models.PlayModelContextArea.MembershipDesigner)
    {
        returnId = question.Id.ToString();
    }

    string answerText = string.Empty;
    
    if (answer != null)
    {
        answerText = ((answer.AnswerBool ?? false) ? "checked" : "");
    }
    
    string prompt = presented.Prompt;
}

<div class="question checkbox @(program.ExpandString(question.HtmlPresentation.CustomClass))" style="@(program.ExpandString(question.HtmlPresentation.CustomStyling))"  data-presentable-name="@(string.IsNullOrEmpty(question.Name) ? "blank" : question.Name)">
       
    <label class="checkbox inline" style="@(program.ExpandString(question.HtmlPresentation.CustomStyling))">
        @if (question.HtmlPresentation.LabelPlacement == ConceptCave.Checklist.Interfaces.HtmlPresentationHintLabelPlacement.Left && prompt != null && prompt.Length > 0 && !question.HidePrompt)
        {
            @Html.Raw(@prompt)
        }
        <input type="checkbox" id="@presented.Id" name="@presented.Id" @(answerText)>
        @if (question.HtmlPresentation.LabelPlacement == ConceptCave.Checklist.Interfaces.HtmlPresentationHintLabelPlacement.Right && prompt != null && prompt.Length > 0 && !question.HidePrompt)
        {
            @Html.Raw(@prompt)
        }
    </label>

    @if (question.AllowNotesOnAnswer == true)
    { 
    <button class="btn" type="button" id="notes@(presented.Id)"><i class="icon-book"></i>&nbsp;<translate>Notes</translate></button>
    }
    <p class="help-block" >@Html.Raw(presented.Note)</p>

    @Html.Partial("~/Views/Play/RenderQuestionValidationResult.cshtml", Model.InvalidReasons)
</div>

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('addItem', @Html.Raw(Json.Encode(new ConceptCave.www.Models.JSONDataModelItem() { Id = returnId })));

        var nextHandler = function(args) {
            // get the answer object for us and then give it a property that is the value of our answer
            var item = $("body").checklistplayer('getItem', '@returnId');
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.CheckboxQuestionAnswerModelItemConverter.AnswerPropertyName', Value: $("#@presented.Id").is(':checked') });
        };

        var listener = { beforeNext: nextHandler };

        $("body").checklistplayer('addListener', listener);

        $("#notes@(presented.Id)").button({ icons: { primary: 'ui-icon-document'}, text: false});
        $("#notes@(presented.Id)").click(function() {
            $("#notes@(presented.Id)").trigger('notesrequired', '@presented.Id.ToString()');
        });

        $("#@presented.Id").numeric();
    })
</script>

src/ConceptCave.www/Views/Play/RenderFinishingPlayer.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModelItem
@{
    this.Layout = null;
}

<p translate>You are about to complete the checklist, click the button below to finish the checklist</p>

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('finishing');
    })
</script>

src/ConceptCave.www/Views/Play/RenderFreeTextPlayer.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModelItem
@{
    this.Layout = null;

    ConceptCave.Checklist.Interfaces.ILingoProgram program = Model.PlayerModel.Program;
    ConceptCave.Checklist.Interfaces.IPresentedQuestion presented = (ConceptCave.Checklist.Interfaces.IPresentedQuestion)Model.Presented;
    ConceptCave.Checklist.Editor.FreeTextQuestion question = (ConceptCave.Checklist.Editor.FreeTextQuestion)presented.Question;
    var answer = presented.GetAnswer() as ConceptCave.Checklist.Interfaces.IFreeTextAnswer;

    var returnId = presented.Id.ToString();
    if(Model.PlayerModel.Context.Area == ConceptCave.www.Areas.Player.Models.PlayModelContextArea.MembershipDesigner)
    {
        returnId = question.Id.ToString();   
    }
    
    string answerText = string.Empty;
    
    if (answer != null)
    {
        answerText = (answer.AnswerValue ?? "").ToString();
    }
    string prompt = presented.Prompt;

}

<div class="question freetext @(program.ExpandString(question.HtmlPresentation.CustomClass))" style="@(program.ExpandString(question.HtmlPresentation.CustomStyling))" data-presentable-name="@(string.IsNullOrEmpty(question.Name) ? "blank" : question.Name)">
    @if (prompt != null && prompt.Length > 0 && !question.HidePrompt)
    {
        <h4>@Html.Raw(prompt)</h4>
    }
    <div class="control-group">
        <div class="controls">
            <div class="input-append">
                @if (question.AllowMultiLine == false)
                { 
                    <input type="text" id="@presented.Id" name="@presented.Id" value="@answerText" />
                }
                else
                { 
                    <textarea  id="@presented.Id" name="@presented.Id" rows="10">@answerText</textarea>
                }
                @if (question.AllowNotesOnAnswer == true)
                { 
                <button class="btn" type="button" id="notes@(presented.Id)"><i class="icon-book"></i>&nbsp;<translate>Notes</translate></button>
                }
                <p class="help-block" >@Html.Raw(presented.Note)</p>
            </div>
        </div>
    </div>
    @Html.Partial("~/Views/Play/RenderQuestionValidationResult.cshtml", Model.InvalidReasons)
</div>

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('addItem', @Html.Raw(Json.Encode(new ConceptCave.www.Models.JSONDataModelItem() { Id = returnId })));

        @if (question.AllowMultiLine == true)
        {
/*        <text>
            $('#@(presented.Id)').focus(
            function() 
            { 
                $('#@(presented.Id)').redactor({buttons:['html', '|', 'formatting', '|', 'bold', 'italic', 'deleted', '|', 'unorderedlist', 'orderedlist', 'outdent', 'indent', '|', 'table', 'link', '|', 'fontcolor', 'backcolor', '|', 'alignleft', 'aligncenter', 'alignright', 'justify', '|','horizontalrule']});
            });

            $('#@(presented.Id)').blur(
            function() 
            { 
                $('#@(presented.Id)').destroyEditor();
            });

                </text>*/
        <text>
            $('#@(presented.Id)').redactor({buttons:['html', '|', 'formatting', '|', 'bold', 'italic', 'deleted', '|', 'unorderedlist', 'orderedlist', 'outdent', 'indent', '|', 'table', 'link', '|', 'fontcolor', 'backcolor', '|', 'alignleft', 'aligncenter', 'alignright', 'justify', '|','horizontalrule']});
        </text>
        }

        var nextHandler = function(args) {
            // get the answer object for us and then give it a property that is the value of our answer
            var item = $("body").checklistplayer('getItem', '@returnId');
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.FreeTextQuestionAnswerModelItemConverter.AnswerPropertyName', Value: $("#@presented.Id").val() });
        };

        var listener = { beforeNext: nextHandler };

        $("#notes@(presented.Id)").button({ icons: { primary: 'ui-icon-document'}, text: false});
        $("#notes@(presented.Id)").click(function() {
            $("#notes@(presented.Id)").trigger('notesrequired', '@presented.Id.ToString()');
        });

        $("body").checklistplayer('addListener', listener);
    })
</script>

src/ConceptCave.www/Views/Play/RenderGeoLocationPlayer.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModelItem
@{
    this.Layout = null;

    var uniqueId = Guid.NewGuid().ToString();
    var displayId = "display" + uniqueId;

    ConceptCave.Checklist.Interfaces.ILingoProgram program = Model.PlayerModel.Program;
    ConceptCave.Checklist.Interfaces.IPresentedQuestion presented = (ConceptCave.Checklist.Interfaces.IPresentedQuestion)Model.Presented;
    ConceptCave.Checklist.Editor.GeoLocationQuestion question = (ConceptCave.Checklist.Editor.GeoLocationQuestion)presented.Question;
    var answer = presented.GetAnswer() as ConceptCave.Checklist.Interfaces.IGeoLocationAnswer;

    var returnId = presented.Id.ToString();
    if (Model.PlayerModel.Context.Area == ConceptCave.www.Areas.Player.Models.PlayModelContextArea.MembershipDesigner)
    {
        returnId = question.Id.ToString();
    }

    string answerText = string.Empty;
    string prompt = presented.Prompt;

}

<div class="question geocode @(program.ExpandString(question.HtmlPresentation.CustomClass))" style="@(program.ExpandString(question.HtmlPresentation.CustomStyling))"  data-presentable-name="@(string.IsNullOrEmpty(question.Name) ? "blank" : question.Name)">
    @if (prompt != null && prompt.Length > 0 && !question.HidePrompt)
    {
        <h4>@Html.Raw(prompt)</h4>
    }
    <div class="control-group">
        <div class="controls">
            <div>
                <div id="@uniqueId" style="display:none; clear:both" translate>
                Please wait, calculating location ...
                </div>
                <div id="haslocation@(uniqueId)" class="row-fluid" style="display:none;clear:both">
                    <div class="span10" id="haslocationMessage@(uniqueId)"></div>
                    <div class="span2"><a id="refreshLocation@(uniqueId)" class="btn btn-info" translate>Refresh</a></div>
                </div>
                @if (question.AllowNotesOnAnswer == true)
                { 
                <button class="btn" type="button" id="notes@(presented.Id)"><i class="icon-book"></i>&nbsp;<translate>Notes</translate></button>
                }
                <p class="help-block" >@Html.Raw(presented.Note)</p>
            </div>
        </div>
    </div>
    @Html.Partial("~/Views/Play/RenderQuestionValidationResult.cshtml", Model.InvalidReasons)
</div>

<script type="text/javascript">
    $(function () {
        $("body").checklistplayer('addItem', @Html.Raw(Json.Encode(new ConceptCave.www.Models.JSONDataModelItem() { Id = returnId })));

        var showHasLocation = function(lat, lng, acc, status)
        {
            var statusMessage = "";
            if(status != undefined && status == "Inaccurate")
            {
                statusMessage = $ng_translate.instant("<span style='color:red'>This measurment is innacurate, you should consider hitting refresh</span>");
            }

            $("#haslocationMessage@(uniqueId)").html("<div class='alert alert-success'>" + $ng_translate.instant("You are currently located at {{ lat }}, {{ lng }} accurate to {{ accuracy }}m {{ statusMessage }}", { lat: lat, lon: lng, accuracy:acc, statusMessage: statusMessage }) + "</div>");
            $("#@uniqueId").hide('slide');
            $("#haslocation@(uniqueId)").show('slide');
        }

        var positionCallback = function(position) {
            var item = $("body").checklistplayer('getItem', '@returnId');
            item.Properties = [];
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.GeoLocationQuestionAnswerModelItemConverter.LattitudeAnswerPropertyName', Value: position.coords.latitude });
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.GeoLocationQuestionAnswerModelItemConverter.LongitudeAnswerPropertyName', Value: position.coords.longitude });
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.GeoLocationQuestionAnswerModelItemConverter.AccuracyAnswerPropertyName', Value: position.coords.accuracy});

            showHasLocation(position.coords.latitude, position.coords.longitude, position.coords.accuracy, position.status);
        };

        var errorCallback = function(message) {
            var item = $("body").checklistplayer('getItem', '@returnId');
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.GeoLocationQuestionAnswerModelItemConverter.ErrorAnswerPropertyName', Value: message.message });
            $("#@uniqueId").html("<div class='alert alert-error'>" + $ng_translate.instant("A problem was encountered getting your location: {{ message }}", { message: message.message }) + "</div>");
            $("#@uniqueId").effect("highlight", { 'color': '#ccffcc' }, 3000);
        };

        var getLocation = function()
        {
            $("#@uniqueId").show('slide');
            navigator.geolocation.getCurrentPosition(positionCallback, errorCallback, { enableHighAccuracy: true }); 
        }

        if(navigator.geolocation)
        {
            getLocation();  
        }
        else
        {
            var item = $("body").checklistplayer('getItem', '@returnId');
            item.Properties.push({ Name: '@ConceptCave.www.Areas.Player.Models.GeoLocationQuestionAnswerModelItemConverter.ErrorAnswerPropertyName', Value: "Geocode not supported" });
            $("#@uniqueId").html("Geocode not supported");
            $("#@uniqueId").effect("highlight", { 'color': '#ccffcc' }, 3000);
        }

        var nextHandler = function(args) {
        };

        var listener = { beforeNext: nextHandler };

        $("#notes@(presented.Id)").button({ icons: { primary: 'ui-icon-document'}, text: false});
        $("#notes@(presented.Id)").click(function() {
            $("#notes@(presented.Id)").trigger('notesrequired', '@presented.Id.ToString()');
        });

        $("#refreshLocation@(uniqueId)").click(function() {
            $("#haslocation@(uniqueId)").hide("slide");
            getLocation();
        });

        $("body").checklistplayer('addListener', listener);
    })
</script>

src/ConceptCave.www/Views/Play/RenderLabelPlayer.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModelItem
@{
    this.Layout = null;

    ConceptCave.Checklist.Interfaces.ILingoProgram program = Model.PlayerModel.Program;
    ConceptCave.Checklist.Interfaces.IPresentedQuestion presented = (ConceptCave.Checklist.Interfaces.IPresentedQuestion)Model.Presented;
    ConceptCave.Checklist.Editor.LabelQuestion question = (ConceptCave.Checklist.Editor.LabelQuestion)presented.Question;
    string prompt = presented.Prompt;
}

<div class="question labelquestion" data-presentable-name="@(string.IsNullOrEmpty(question.Name) ? "blank" : question.Name)">
    <div class="@(program.ExpandString(question.HtmlPresentation.CustomClass))" style="@(program.ExpandString(question.HtmlPresentation.CustomStyling))">
    @if (prompt != null && prompt.Length > 0 && !question.HidePrompt)
    {
        <h3>@Html.Raw(prompt)</h3>
    }
      <p>@Html.Raw(program.ExpandString(question.Text))</p>
        @Html.Partial("~/Views/Play/RenderQuestionValidationResult.cshtml", Model.InvalidReasons)
    </div>
</div>

src/ConceptCave.www/Views/Play/RenderProgressIndicatorPlayer.cshtml
@model ConceptCave.www.Areas.Player.Models.PlayerModelItem
@{
    this.Layout = null;

    ConceptCave.Checklist.Interfaces.ILingoProgram program = Model.PlayerModel.Program;
    ConceptCave.Checklist.Interfaces.IPresentedQuestion presented = (ConceptCave.Checklist.Interfaces.IPresentedQuestion)Model.Presented;
    ConceptCave.Checklist.Editor.ProgressIndicatorQuestion question = (ConceptCave.Checklist.Editor.ProgressIndicatorQuestion)presented.Question;
    string prompt = presented.Prompt;

}

<div class="question progress @(program.ExpandString(question.HtmlPresentation.CustomClass))" style="@(program.ExpandString(question.HtmlPresentation.CustomStyling))" data-presentable-name="@(string.IsNullOrEmpty(question.Name) ? "blank" : question.Name)">
    @if (prompt != null && prompt.Length > 0 && !question.HidePrompt)
    {
        <h3>@Html.Raw(prompt)</h3>
    }
    <div class="progress progress-info">
        <div class="bar" style="width:@(question.ValueAsPercentage * 100)%">@((question.ValueAsPercentage * 100).ToString("##.##"))%</div>
    </div>
</div>

src/ConceptCave.www/Views/Play/SaveNoteAttachment.cshtml
@model ConceptCave.www.Areas.Player.Models.NotesModel

@{
    this.Layout = null;

    List<ConceptCave.www.Areas.Player.Models.NotesAttachmentModel> attachments = Model.Attachments;
}

@Html.Partial("DisplayNotesAttachments", attachments)